peerDependencyRules:
  allowedVersions:
    '@vee-validate/zod>zod': '4'
    zod: '4'

allowBuilds:
  '@parcel/watcher': false
  '@tailwindcss/oxide': false
  esbuild: false
  unrs-resolver: false
  vue-demi: false
